name: Build

on:
  pull_request: {}
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.2
      - name: Install Node.js
        run: |
          curl -fsSL https://nodejs.org/dist/v22.10.0/node-v22.10.0-linux-x64.tar.xz -o node-v22.10.0-linux-x64.tar.xz
          sudo tar -xJf node-v22.10.0-linux-x64.tar.xz -C /usr/local
          echo "/usr/local/node-v22.10.0-linux-x64/bin" >> $GITHUB_PATH
      - name: Restore NPM node_modules
        uses: actions/cache/restore@v4.1.2
        with:
          path: node_modules
          key: ${{ runner.os }}-node_modules-${{ hashFiles('pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-node_modules-
      - name: Install pnpm and dependencies
        run: |
          pnpm install
      - name: Check Node
        run: |
            set +e
            which node
            which npm
            which yarn
            which pnpm
            which corepack
            node -v
            npm -v
            yarn --version
            pnpm --version
            corepack --version
            echo $PATH
      - name: Cache NPM dependencies
        uses: actions/cache@v4.1.2
        with:
          path: node_modules
          key: ${{ runner.os }}-node_modules-${{ hashFiles('pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-node_modules-
      - name: Assume role using OIDC
        uses: aws-actions/configure-aws-credentials@v4.0.2
        with:
          aws-region: ${{ secrets.CDK_DEPLOY_REGION }}
          role-to-assume: ${{ secrets.AWS_ROLE }}
          role-session-name: ${{ secrets.AWS_SESSION_NAME }}
      - name: Run build
        env:
          CDK_DEPLOY_ACCOUNT: ${{ secrets.CDK_DEPLOY_ACCOUNT }}
          CDK_DEPLOY_REGION: ${{ secrets.CDK_DEPLOY_REGION }}
          CDK_DEFAULT_ACCOUNT: ${{ secrets.CDK_DEFAULT_ACCOUNT }}
          CDK_DEFAULT_REGION: ${{ secrets.CDK_DEFAULT_REGION }}
          AWS_REGION: ${{ secrets.CDK_DEPLOY_REGION }}
        run: pnpm run diff
